### ISSUE TITLE
Not able to get the "Text" value of the "Selected"

### ISSUE THREAD

**Issue by MassaM-SDC** [losmicar/bselect#7]
Hi Dear,

Nice component and thank you for sharing.

With this data:

`	let testData = {
					1 : "Be Right Back", 
					2 : "Do Not Distrub", 
					3 : "Available", 
					4 : "All Day Out"
					};
`

I have an issue with getting the text part of the selected. By using the code below:

`$('#current-status-officer-board').html('Officer Status:'+$('#select-officer-status').bselect("getSelected"));`

as I can only get the numeric key.

And if this type of data was used as below:

`	let testData = {
					"BRB" : "Be Right Back", 
					"DND" : "Do Not Distrub", 
					"AVL" : "Available", 
					"ADO" : "All Day Out"
					};`

Then it does not set the **_preselect_** as in `selected : 3`, nor it reports the `getSelected`.

`$('#select-deputy-status').bselect({
		data : testData, 
		search : true, 
		selected : 3,
		width : '200px',
		defaultText : "Select..."
	});`

Also a feature request would be that, if it can be enhanced to receive a JSON file format as sometime loading the options
from an API is required.

I have a simple _"test.html"_ in the attached _"test.zip"_ file illustrating the problem.

[test.zip](https://github.com/losmicar/bselect/files/6290928/test.zip)

Much appreciated.

**Comment by losmicar** [comment]
Hi,

Thank you for your feedback!

I've added "getSelectedText" method to support your request getting selected items in CSV format (containing text values of the input data).

Also in second example your implementation is wrong.
`let testData = { "BRB" : "Be Right Back", "DND" : "Do Not Distrub", "AVL" : "Available", "ADO" : "All Day Out" };`

**Preselection is not working by index.** You can't use index (3) to preselect third item if key is not equal to that index, so obviously to preselect any of items from the object above you should use `selected : "AVL"` instead of `selected : 3`. 

As for the feature request data is received in JSON format and this component was originally build for that reason, not sure what's your use case but it's already widely used with preloaded data from an APIs.
